"""activity_log table

Revision ID: 57986d22ef92
Revises: f53f8d237a27
Create Date: 2018-09-19 22:43:40.528714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57986d22ef92'
down_revision = 'f53f8d237a27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('activity', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_log_activity'), ['activity'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_log_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_log_username'), ['username'], unique=True)

    with op.batch_alter_table(u'timelog', schema=None) as batch_op:
        batch_op.drop_index('ix_timelog_activity')
        batch_op.drop_index('ix_timelog_timestamp')

    op.drop_table('timelog')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.VARCHAR(length=140), nullable=True))

    op.create_table('timelog',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('count', sa.INTEGER(), nullable=True),
    sa.Column('activity', sa.VARCHAR(length=64), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table(u'timelog', schema=None) as batch_op:
        batch_op.create_index('ix_timelog_timestamp', ['timestamp'], unique=False)
        batch_op.create_index('ix_timelog_activity', ['activity'], unique=False)

    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_log_username'))
        batch_op.drop_index(batch_op.f('ix_activity_log_timestamp'))
        batch_op.drop_index(batch_op.f('ix_activity_log_activity'))

    op.drop_table('activity_log')
    # ### end Alembic commands ###
