"""timelog table

Revision ID: f53f8d237a27
Revises: ef37c4a96e68
Create Date: 2018-09-19 21:42:14.517585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f53f8d237a27'
down_revision = 'ef37c4a96e68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timelog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('activity', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('timelog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_timelog_activity'), ['activity'], unique=False)
        batch_op.create_index(batch_op.f('ix_timelog_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table(u'post', schema=None) as batch_op:
        batch_op.drop_index('ix_post_timestamp')

    op.drop_table('post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('body', sa.VARCHAR(length=140), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table(u'post', schema=None) as batch_op:
        batch_op.create_index('ix_post_timestamp', ['timestamp'], unique=False)

    with op.batch_alter_table('timelog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_timelog_timestamp'))
        batch_op.drop_index(batch_op.f('ix_timelog_activity'))

    op.drop_table('timelog')
    # ### end Alembic commands ###
